apiVersion: v1
kind: Service
metadata:
  name: sklearn-iris-external
  namespace: default
spec:
  type: NodePort
  selector:
    serving.kserve.io/inferenceservice: sklearn-iris
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100

