apiVersion: v1
kind: Secret
metadata:
  name: keda-aws-msk-credentials
  namespace: demo
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{"update your key"}}
  AWS_SECRET_ACCESS_KEY: {{"update your key"}}