kind: NetworkPolicy
apiVersion: projectcalico.org/v3
metadata:
  name: allow-golang-ingress
  namespace: demo
spec:
  selector: app == "wezvagolangbootapp"
  ingress:
    - action: Allow
      protocol: TCP
      destination:
        ports:
          - 8081
  egress:
    - action: Allow
  types:
    - Ingress
    - Egress
