apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-aws-creds
  namespace: logging
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_REDACTED_BY_SYNC"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_REDACTED_BY_SYNC"
