apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-aws-creds
  namespace: logging
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIAQAYRTNCWJDAC27ET"
  AWS_SECRET_ACCESS_KEY: "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"
