apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Parser        docker
        Tag           kube.*
        Refresh_Interval 5
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On
        Read_from_Head   On
        Buffer_Max_Size  512k
        DB               /var/log/flb_kube.db

    [FILTER]
        Name             kubernetes
        Match            kube.*
        Kube_Tag_Prefix  kube.var.log.containers.
        Merge_Log        On
        K8S-Logging.Parser On
        K8S-Logging.Exclude Off

    [OUTPUT]
        Name            opensearch
        Match           *
        Host            81itfnxpbr47epl1fnxj.ap-south-1.aoss.amazonaws.com
        AWS_Service_Name aoss
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      ap-south-1
        Index           index/wezvatech-collection
        Trace_Error     On
        Suppress_Type_Name On
        Logstash_Format On
        Replace_Dots    On

    [OUTPUT]
        Name          s3
        Match         *
        bucket        test-wezva
        region        ap-south-1
        s3_key_format /logs/$TAG/$UUID.log
        store_dir     /var/log/s3
        upload_chunk_size 10M
        upload_timeout 60
        use_put_object On

  parsers.conf: |
    [PARSER]
        Name         docker
        Format       json
        Time_Key     time
        Time_Format  %Y-%m-%dT%H:%M:%S.%L
        Time_Keep    On
