apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wezvagolangbootapp
  name: wezvagolang-canarysvc
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
      nodePort: 32100
  selector:
    app: wezvagolangbootapp
status:
  loadBalancer: {}