apiVersion: v1
kind: ConfigMap
metadata:
  name: wezvagolangcm
  namespace: demo
data:
  # MySQL
  host: mysql-svc:3306
  dbname: library

  # Kafka
  kafka_brokers: kafka-cluster-kafka-bootstrap.kafka:9098
  kafka_topic: payments
  kafka_consumer_group: golang-group

  # Valkey
  VALKEY_HOST: valkey-primary.demo.svc.cluster.local
  VALKEY_PORT: "6379"
  VALKEY_DB: "0"
  VALKEY_TLS_ENABLED: "false"