apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: default
  annotations:
    # Tells KServe's internal agent to associate these credentials with the model downloader
    serving.kserve.io/s3-secret-uuid: "true"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AWS_ACCESS_KEY_ID_REDACTED_BY_SYNC"
  AWS_SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY_REDACTED_BY_SYNC"
  AWS_DEFAULT_REGION: "ap-south-1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: default
secrets:
  - name: s3-secret
