apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kserve-pods'
              static_configs:
                - targets: ['fraud-predictor-metrics.default.svc.cluster.local:8082']

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "otel"
      debug:
        verbosity: detailed

    processors:
      batch:

    extensions:
      health_check:

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheus, debug]

