apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.modelName }}-external
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    serving.kserve.io/inferenceservice: {{ .Values.modelName }}
  ports:
    - name: http-inference
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePorts.inference }}
    - name: prometheus-metrics
      protocol: TCP
      port: 8082       
      targetPort: 8082 
      nodePort: {{ .Values.service.nodePorts.metrics }}

