apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: database-secret
  namespace: demo
spec:
  vaultAuthRef: wezva-auth

  mount: internal
  path: database/config
  type: kv-v2

  destination:
    name: database-secret
    create: true

  refreshAfter: 30s
