apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: wezvanodejsapp
  name: notification-svc
  namespace: demo
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: wezvanodejsapp
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102