apiVersion: v1
kind: Service
metadata:
  name: wezvanodejsapp-service
  namespace: demo
  labels:
    app.kubernetes.io/name: wezvanodejsapp
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/name: wezvanodejsapp

