apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: database-ssl-secret
  namespace: demo
spec:
  vaultAuthRef: wezva-auth

  mount: internal
  path: database/ssl
  type: kv-v2

  destination:
    name: database-ssl-secret
    create: true
    type: kubernetes.io/tls

  refreshAfter: 30s

