name: Validate Main Source

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    name: Validate source branch
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"

          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Only DEV branch is allowed to merge into MAIN."
            echo "Current source branch: ${{ github.head_ref }}"
            exit 1
          fi

          echo "✅ DEV is allowed to merge into MAIN."